services:
  postgres:
    container_name: sportscape-postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - sportscape-postgres
    restart: unless-stopped
  pgadmin:
    container_name: sportscape-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - sportscape-postgres
    restart: unless-stopped

networks:
  sportscape-postgres:
    driver: bridge
#  spring:
#    driver: bridge

volumes:
  postgres:
  pgadmin: